title: Aidan M # your name (or website title) here
logo: "https://avatars.githubusercontent.com/u/24928676?v=4" # your photo (or logo) here
description:
  

plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
