title: Aidan M # your name (or website title) here
logo: "https://avatars.githubusercontent.com/u/24928676?v=4" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br><br>
  Skills and Stuff -
  Rust, Dart, Python
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="1ad87a38-a4df-4255-a8ea-cdd8325bc295" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  
  <br><br>
  <a href="https://github.com/AIDXNZ">View My GitHub Profile</a> 
  
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
